#!/bin/bash
curl -s --compressed "https://cutefishos-ubuntu.github.io/packages/key/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/KEY.gpg >/dev/null

sudo curl -s --compressed -o /etc/apt/sources.list.d/cutefish.list "https://cutefishos-ubuntu.github.io/packages/cutefish.list"

sudo apt update
