name: Build and sign Debian repository

on:
  push:
  pull_request:
  workflow_dispatch:
  
  watch:
    types: [started]

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install gnupg dpkg-dev -y

      - name: Create Packages file
        run: dpkg-scanpackages --multiversion . > Packages

      - name: Compress Packages file
        run: gzip -k -f Packages

      - name: Create Release file
        run: apt-ftparchive release . > Release

      - name: Create Release signature file
        run: gpg --default-key "B7BCE7683AAE5AC246AC171C48E66A3508ECE7D9 -abs -o - Release > Release.gpg

      - name: Create InRelease file
        run: gpg --default-key "B7BCE7683AAE5AC246AC171C48E66A3508ECE7D9" --clearsign -o - Release > InRelease
