name: Build and Sign Debian Packages

on:
  push:
  pull_request:
 
  paths:
    - '**'
    
  workflow_dispatch:

jobs:
  build-and-sign-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev gnupg2

      - name: Import secret key
        run: |
          gpg --export-secret-keys "titenko.m@gmail.com" > my-private-key.asc
          gpg --import my-private-key.asc

      - name: Export public key
        run: |
          gpg --armor --export "titenko.m@gmail.com" > KEY.gpg

      - name: Create Debian packages
        run: |
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          apt-ftparchive release . > Release

      - name: Sign Release with GPG
        run: |
          gpg --default-key "titenko.m@gmail.com" -abs -o - Release > Release.gpg
          gpg --default-key "titenko.m@gmail.com" --clearsign -o - Release > InRelease
